import { chromium } from 'playwright';
import { existsSync, readdirSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import assert from 'node:assert/strict';

const base = process.env.DEPLOY_URL;
if (!base?.startsWith('https://')) throw new Error('Set DEPLOY_URL to the deployed HTTPS origin');
const cache = join(homedir(), 'Library/Caches/ms-playwright');
const cached = existsSync(cache) ? readdirSync(cache).filter(n => /^chromium_headless_shell-\d+$/.test(n)).sort().reverse().map(n => join(cache, n, `chrome-headless-shell-mac-${process.arch === 'arm64' ? 'arm64' : 'x64'}`, 'chrome-headless-shell')).find(existsSync) : undefined;
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH || (existsSync(chromium.executablePath()) ? undefined : cached) });
const errors = [], checks = [];
const record = name => { checks.push(name); console.log(`PASS ${name}`); };
await mkdir('artifacts', { recursive: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(60000);
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  const worlds = [];
  page.on('request', r => { if (/\/worlds\/.*\.bin$/.test(r.url())) worlds.push(r.url()); });
  await page.goto(base);
  await page.getByText('云端体验', { exact: false }).waitFor();
  await page.locator('.atlas-loading').waitFor({ state: 'hidden' });
  assert.equal(worlds.length, 0);
  await page.screenshot({ path: 'artifacts/cloudflare-globe.png' });
  record('HTTPS production globe loads without preloading either world');
  await page.getByRole('button', { name: '下一步，表达心情', exact: true }).click();
  await page.locator('#atlas-intent').fill('想去森林，听树叶的声音，让自己安定下来。');
  const response = page.waitForResponse(r => r.url().endsWith('/api/route'));
  await page.getByRole('button', { name: '寻找适合的目的地', exact: false }).click();
  const route = await (await response).json();
  await page.locator('.stage-explore').waitFor();
  assert.equal(worlds.length, 0);
  assert.equal(await page.locator('.destination-card').count(), 0);
  assert.equal(route.world, 'forest');
  if (process.env.REQUIRE_AI === '1') assert.equal(route.mode, 'ai-gateway');
  if (route.mode === 'ai-gateway') await page.locator('.atlas-recommendation').getByText('AI 推荐', { exact: false }).waitFor();
  else await page.locator('.atlas-recommendation').getByText('本地规则', { exact: false }).waitFor();
  record(`production recommendation is honestly labeled ${route.mode}`);
  for (const [place, id] of [['屋久岛', 'forest'], ['帕劳', 'abyss']]) {
    await page.getByRole('button', { name: `选择目的地：${place}`, exact: true }).click();
    await page.getByRole('button', { name: `进入${place}世界`, exact: true }).click();
    await page.locator(`.world-${id}.view-transform`).waitFor();
    await page.locator('.scene-message').waitFor({ state: 'hidden' });
    await page.locator('.scene canvas').waitFor();
    assert.equal(await page.locator('canvas').count(), 1);
    await page.getByRole('button', { name: '深度平静', exact: true }).click();
    await page.waitForTimeout(2500);
    await page.screenshot({ path: `artifacts/cloudflare-${id}.png` });
    record(`${place} point cloud loads from Cloudflare and enters the interactive world`);
    await page.getByRole('button', { name: '返回地球', exact: true }).click();
    await page.locator('.atlas-loading').waitFor({ state: 'hidden' });
  }
  await page.getByRole('button', { name: '设备接入', exact: true }).click();
  await page.getByText('实时桥接服务已连接', { exact: false }).waitFor();
  const sensorStatus = await page.evaluate(async () => (await fetch('/api/frame', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ attention: .7, relaxation: .8, HR: 64, signalQuality: 1 }) })).status);
  assert.equal(sensorStatus, 200);
  record('browser session receives live cloud WebSocket data');
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
  await mobile.goto(base);
  await mobile.locator('.atlas-loading').waitFor({ state: 'hidden' });
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await mobile.screenshot({ path: 'artifacts/cloudflare-mobile.png' });
  record('mobile production layout has no horizontal overflow');
  assert.deepEqual(errors, []);
  await writeFile('artifacts/cloudflare-browser.json', JSON.stringify({ base, checks, errors, aiMode: route.mode, gatewayRequestId: route.gatewayRequestId, at: new Date().toISOString() }, null, 2));
} finally { await browser.close(); }
