// Generated by scripts/generate-landmarks.mjs
export const POINT_COUNTS = {
  "abyss": 195160,
  "forest": 280050,
  "great-wall": 105680,
  "fuji": 127555,
  "eiffel": 111640,
  "colosseum": 186600,
  "giza": 122000,
  "taj-mahal": 119164,
  "machu-picchu": 119002,
  "grand-canyon": 148000,
  "sydney-opera": 139950,
  "iguazu": 121000
};
