// Generated by scripts/import-scenes.py; payloads are stored in R2.
export const SCENE_ASSETS = Object.freeze([
  {
    "id": "scene-01",
    "count": 400000,
    "bytes": 12800000,
    "sha256": "88af367ce8c4f61702cdfb885a950e5192498bc23b8995075d742d959a24dcc5",
    "key": "scenes/scene-01/88af367ce8c4f617.bin",
    "url": "/scene-data/scene-01/88af367ce8c4f617.bin",
    "safeYaw": 3,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-02",
    "count": 387650,
    "bytes": 12404800,
    "sha256": "4d29ffae4f13f539be2d3a6a32ab81314489db5a40ae8d47555f5c6daaf2e1db",
    "key": "scenes/scene-02/4d29ffae4f13f539.bin",
    "url": "/scene-data/scene-02/4d29ffae4f13f539.bin",
    "safeYaw": 3,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-03",
    "count": 400000,
    "bytes": 12800000,
    "sha256": "60e6ed88a933ddcf3b30921e4de8c8ab59093e47894caedcd4e5620bf42845a6",
    "key": "scenes/scene-03/60e6ed88a933ddcf.bin",
    "url": "/scene-data/scene-03/60e6ed88a933ddcf.bin",
    "safeYaw": 6,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-04",
    "count": 400000,
    "bytes": 12800000,
    "sha256": "1b39e25d9354503349331a865ace5bfbbf1000fd379b368db04e9279646f4167",
    "key": "scenes/scene-04/1b39e25d93545033.bin",
    "url": "/scene-data/scene-04/1b39e25d93545033.bin",
    "safeYaw": 4,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-05",
    "count": 400000,
    "bytes": 12800000,
    "sha256": "24397b263295bd4813e30ef75eb7e5cf9eb91448bee37c8197f5e62b14329324",
    "key": "scenes/scene-05/24397b263295bd48.bin",
    "url": "/scene-data/scene-05/24397b263295bd48.bin",
    "safeYaw": 2,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-06",
    "count": 400000,
    "bytes": 12800000,
    "sha256": "8f2dbf5114eac3d96695b5bb8586696c9ea5308d9e8bdc4dbfacb641eb7557ac",
    "key": "scenes/scene-06/8f2dbf5114eac3d9.bin",
    "url": "/scene-data/scene-06/8f2dbf5114eac3d9.bin",
    "safeYaw": 4,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-07",
    "count": 399157,
    "bytes": 12773024,
    "sha256": "4024414ec21690cf14e1de87899c182d2834492db79882746770f395b1402040",
    "key": "scenes/scene-07/4024414ec21690cf.bin",
    "url": "/scene-data/scene-07/4024414ec21690cf.bin",
    "safeYaw": 6,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-08",
    "count": 398773,
    "bytes": 12760736,
    "sha256": "3ec92137b60128855c263784e4590ef4b0ea80c71b5564bdea652f584785b5cf",
    "key": "scenes/scene-08/3ec92137b6012885.bin",
    "url": "/scene-data/scene-08/3ec92137b6012885.bin",
    "safeYaw": 4,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-09",
    "count": 400000,
    "bytes": 12800000,
    "sha256": "3ea0e573c3239005eda533880eebb1b104d493845c78263ecb369542c2f193aa",
    "key": "scenes/scene-09/3ea0e573c3239005.bin",
    "url": "/scene-data/scene-09/3ea0e573c3239005.bin",
    "safeYaw": 2,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-10",
    "count": 400000,
    "bytes": 12800000,
    "sha256": "d7fa229ef16d5eb311b1370126b58e566b7340f3100ec1d91530c65deddae524",
    "key": "scenes/scene-10/d7fa229ef16d5eb3.bin",
    "url": "/scene-data/scene-10/d7fa229ef16d5eb3.bin",
    "safeYaw": 6,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-11",
    "count": 400000,
    "bytes": 12800000,
    "sha256": "cb96f58b28b077f5ce6c91492f140e7a7c3b46392a463c4acc0875e71bbd3ffb",
    "key": "scenes/scene-11/cb96f58b28b077f5.bin",
    "url": "/scene-data/scene-11/cb96f58b28b077f5.bin",
    "safeYaw": 3,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-12",
    "count": 383173,
    "bytes": 12261536,
    "sha256": "5bd2c4eac32f09fc67a76a524f1ec07fddf623184b854ddb255863462c6348bd",
    "key": "scenes/scene-12/5bd2c4eac32f09fc.bin",
    "url": "/scene-data/scene-12/5bd2c4eac32f09fc.bin",
    "safeYaw": 2,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-13",
    "count": 394073,
    "bytes": 12610336,
    "sha256": "eb58f8a4b366274ce80eed24abefb20509e83bce7ff7ec5668f1c9c3de55cac9",
    "key": "scenes/scene-13/eb58f8a4b366274c.bin",
    "url": "/scene-data/scene-13/eb58f8a4b366274c.bin",
    "safeYaw": 3,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-14",
    "count": 287048,
    "bytes": 9185536,
    "sha256": "ba7757020a08bec71d76e61f9a3d8391f2a4827f0867aeecf6fc22d9bc4b170e",
    "key": "scenes/scene-14/ba7757020a08bec7.bin",
    "url": "/scene-data/scene-14/ba7757020a08bec7.bin",
    "safeYaw": 6,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "video"
  },
  {
    "id": "scene-15",
    "count": 281463,
    "bytes": 9006816,
    "sha256": "caf76a3ad0d838eb110863da8e6b70d50e0d060111cf7658f918559398e3e34f",
    "key": "scenes/scene-15/caf76a3ad0d838eb.bin",
    "url": "/scene-data/scene-15/caf76a3ad0d838eb.bin",
    "safeYaw": 6,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "video"
  },
  {
    "id": "scene-16",
    "count": 398929,
    "bytes": 12765728,
    "sha256": "a170d19b2f4ab262a7b235f0135e8969a50a3e82a3002fc5bc90089af4c788f1",
    "key": "scenes/scene-16/a170d19b2f4ab262.bin",
    "url": "/scene-data/scene-16/a170d19b2f4ab262.bin",
    "safeYaw": 4,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-17",
    "count": 311264,
    "bytes": 9960448,
    "sha256": "2cc8e385408a5bc8f8729f8b1697c829852feb80b1c1ba9786ae0d131ca1ecd5",
    "key": "scenes/scene-17/2cc8e385408a5bc8.bin",
    "url": "/scene-data/scene-17/2cc8e385408a5bc8.bin",
    "safeYaw": 6,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "video"
  },
  {
    "id": "scene-18",
    "count": 391222,
    "bytes": 12519104,
    "sha256": "a5db0c66499fdcd48d6acb6de4f9b232cd702cc23c903de3117c009f54dc662d",
    "key": "scenes/scene-18/a5db0c66499fdcd4.bin",
    "url": "/scene-data/scene-18/a5db0c66499fdcd4.bin",
    "safeYaw": 6,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-19",
    "count": 400000,
    "bytes": 12800000,
    "sha256": "fa9207bc55f11cdb476c1851110dd00b8d13b5a36ce17167172b72f9f3ef69f9",
    "key": "scenes/scene-19/fa9207bc55f11cdb.bin",
    "url": "/scene-data/scene-19/fa9207bc55f11cdb.bin",
    "safeYaw": 4,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  },
  {
    "id": "scene-20",
    "count": 400000,
    "bytes": 12800000,
    "sha256": "1f32965d4b9ec9a6b22e1950b8578fdcb2cc65fa2839e5a7fd00c3fd5aa701c8",
    "key": "scenes/scene-20/1f32965d4b9ec9a6.bin",
    "url": "/scene-data/scene-20/1f32965d4b9ec9a6.bin",
    "safeYaw": 4,
    "camera": {
      "position": [
        3.6240520910761895,
        8.0,
        23.720104300690615
      ],
      "target": [
        0.0,
        3.6,
        -5.0
      ],
      "fov": 49,
      "orbit_x": 0.13
    },
    "sourceKind": "image"
  }
]);
export const sceneAsset = id => SCENE_ASSETS.find(scene => scene.id === id);
export const sceneAssetForPath = path => SCENE_ASSETS.find(scene => scene.url === path);
