"""Import the user-selected archive without publishing private source metadata.

The original 32-byte records stay byte-identical. Large payloads live in R2;
only the public catalogue and immutable content hashes are committed to Git.
"""
import argparse
import array
import hashlib
import json
import math
from pathlib import Path
import sys
import zipfile

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('archive', nargs='?', default=str(ROOT / 'artifacts/scene-clouds-20/精选20_点云_Mindscape.zip'))
args = parser.parse_args()
assets = []
with zipfile.ZipFile(args.archive) as archive:
    manifest = json.loads(archive.read('Mindscape/manifest.json'))
    assert len(manifest['models']) == 20
    for index, model in enumerate(manifest['models'], 1):
        name = f'scene-{index:02d}'
        assert model['id'] == name
        raw = archive.read(f'Mindscape/worlds/{name}.bin')
        digest = hashlib.sha256(raw).hexdigest()
        assert digest == model['bin_sha256']
        assert len(raw) == model['point_count'] * 32
        points = array.array('f', raw)
        if sys.byteorder != 'little':
            points.byteswap()
        assert all(math.isfinite(v) for v in points)
        for j in range(0, len(points), 8):
            assert all(0 <= points[j+k] <= 1 for k in (3, 4, 5))
            assert points[j+6] >= 0 and points[j+7] >= 0
        key = f'scenes/{name}/{digest[:16]}.bin'
        output = ROOT / 'artifacts/scene-clouds-published' / key
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(raw)
        assets.append(dict(id=name, count=model['point_count'], bytes=len(raw), sha256=digest,
            key=key, url=f'/scene-data/{name}/{digest[:16]}.bin',
            safeYaw=model['safe_yaw_degrees'], camera=model['camera'], sourceKind=model['source_kind']))
        print(f'{name}: {model["point_count"]:,} points verified', flush=True)

destination = ROOT / 'src/core/scene-assets.mjs'
destination.write_text('// Generated by scripts/import-scenes.py; payloads are stored in R2.\n'
    + 'export const SCENE_ASSETS = Object.freeze(' + json.dumps(assets, ensure_ascii=False, indent=2) + ');\n'
    + 'export const sceneAsset = id => SCENE_ASSETS.find(scene => scene.id === id);\n'
    + 'export const sceneAssetForPath = path => SCENE_ASSETS.find(scene => scene.url === path);\n')
print(f'Imported {len(assets)} scenes / {sum(a["bytes"] for a in assets):,} bytes')
catalogue = []
for name in ('fuji', 'grand-canyon'):
    terrain = json.loads((ROOT / f'public/terrain/{name}/manifest.json').read_text())
    catalogue.append(dict(id=name, count=terrain['pointCount'], kind='geographic', url=f'/terrain/{name}/manifest.json'))
catalogue.extend(dict(id=a['id'], count=a['count'], kind='image-scene', url=a['url'], sha256=a['sha256']) for a in assets)
(ROOT / 'public/worlds/manifest.json').write_text(json.dumps(catalogue, ensure_ascii=False, indent=2) + '\n')
